import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {chromium} from 'playwright';
import {createStore} from '../src/store.mjs';
import {createApp} from '../src/server.mjs';

test('browser: dashboard setup, answers, controls and CSV work without rendering imported markup',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'job-applier-dashboard-'));
  const store=await createStore(dir);let state='idle';const commands=[];
  const runner={getStatus:()=>({state,todayCount:0,message:state==='running'?'Applying to matching jobs':'Ready',currentJob:null}),start:async options=>{commands.push(['start',options]);state='running';},stop:async()=>{state='idle';commands.push(['stop']);},openBrowser:async()=>{commands.push(['browser']);}};
  const hostileTitle='<img src=x onerror="window.injected=true">';
  await store.createRecord({id:'1001',url:'https://www.linkedin.com/jobs/view/1001/',title:hostileTitle,company:'Example'},'skipped');
  await store.saveQuestions([{key:'are you willing to relocate',label:'Are you willing to relocate?',type:'radio',options:[{label:'Yes',value:'yes'},{label:'No',value:'no'}],jobId:'1001'}]);
  const app=await createApp({dataDir:dir,store,runner,port:0});await app.listen();
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1360,height:960}});
  page.setDefaultTimeout(5000);
  t.after(async()=>{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});});
  await page.goto(app.url);
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  for(const [label,value] of [['First name','Test'],['Last name','Applicant'],['Email','test@example.com'],['Phone','5551234567'],['Job titles','Software Engineer'],['Search location','Chicago']])await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved',{exact:true}).waitFor();
  const resume=join(dir,'test-resume.pdf');await writeFile(resume,'%PDF-1.4 fixture');
  await page.getByLabel('Upload résumé',{exact:true}).setInputFiles(resume);
  await page.getByText('Résumé saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).search.titles[0],'Software Engineer');
  assert.equal((await store.getConfig()).profile.email,'test@example.com');
  await page.getByRole('button',{name:'Answers',exact:true}).click();
  await page.getByLabel('Question',{exact:true}).fill('Years of Java experience');
  await page.getByLabel('Answer',{exact:true}).fill('0');
  await page.getByRole('button',{name:'Save answer',exact:true}).click();
  await page.getByText('Answer saved',{exact:true}).waitFor();
  assert.equal((await store.getAnswers())['years of java experience'],'0');
  await page.getByRole('heading',{name:'Are you willing to relocate?',exact:true}).waitFor();
  await page.getByLabel('Answer for Are you willing to relocate?',{exact:true}).selectOption('No');
  await page.getByRole('button',{name:'Save this answer',exact:true}).click();
  await page.getByRole('button',{name:'Dashboard',exact:true}).click();
  await page.getByRole('button',{name:'Open LinkedIn',exact:true}).click();
  await page.getByText('LinkedIn browser opened',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Start applying',exact:true}).click();
  await page.getByText('Applying to matching jobs',{exact:true}).waitFor();
  assert.equal(commands.filter(command=>command[0]==='start').length,1);
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await page.getByRole('button',{name:'History',exact:true}).click();
  assert.equal(await page.locator('#history-view .job-title').first().textContent(),hostileTitle);
  assert.equal(await page.locator('.job-title img').count(),0);
  assert.equal(await page.evaluate(()=>window.injected),undefined);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'Export CSV',exact:true}).click();
  assert.equal((await downloadPromise).suggestedFilename(),'applications.csv');
  await mkdir(resolve('test-artifacts'),{recursive:true});
  await page.getByRole('button',{name:'Dashboard',exact:true}).click();
  await page.screenshot({path:resolve('test-artifacts/dashboard-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:resolve('test-artifacts/dashboard-mobile.png'),fullPage:true});
});
