import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {chromium} from 'playwright';
import {createStore} from '../src/store.mjs';
import {createApp} from '../src/server.mjs';

test('browser: dashboard setup, answers, controls and CSV work without rendering imported markup',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'job-applier-dashboard-'));
  const store=await createStore(dir);let state='idle';const commands=[];
  const runner={getStatus:()=>({state,todayCount:0,message:state==='running'?'Applying to matching jobs':'Ready',currentJob:null}),start:async options=>{commands.push(['start',options]);state='running';},stop:async()=>{state='idle';commands.push(['stop']);},openBrowser:async()=>{commands.push(['browser']);}};
  const hostileTitle='<img src=x onerror="window.injected=true">';
  await store.createRecord({id:'1001',url:'https://www.linkedin.com/jobs/view/1001/',title:hostileTitle,company:'Example'},'skipped');
  await store.saveQuestions([{key:'are you willing to relocate',label:'Are you willing to relocate?',type:'radio',options:[{label:'Yes',value:'yes'},{label:'No',value:'no'}],jobId:'1001'}]);
  const app=await createApp({dataDir:dir,store,runner,port:0});await app.listen();
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1360,height:960}});
  page.setDefaultTimeout(5000);
  t.after(async()=>{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});});
  await page.goto(app.url);
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  for(const [label,value] of [['First name','Test'],['Last name','Applicant'],['Email','test@example.com'],['Phone','5551234567'],['Job titles','Software Engineer'],['Search location','Chicago']])await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved',{exact:true}).waitFor();
  const resume=join(dir,'test-resume.pdf');await writeFile(resume,'%PDF-1.4 fixture');
  await page.getByLabel('Upload résumé',{exact:true}).setInputFiles(resume);
  await page.getByText('Résumé saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).search.titles[0],'Software Engineer');
  assert.equal((await store.getConfig()).profile.email,'test@example.com');
  await page.getByRole('button',{name:'Answers',exact:true}).click();
  await page.getByLabel('Question',{exact:true}).fill('Years of Java experience');
  await page.getByLabel('Answer',{exact:true}).fill('0');
  await page.getByRole('button',{name:'Save answer',exact:true}).click();
  await page.getByText('Answer saved',{exact:true}).waitFor();
  assert.equal((await store.getAnswers())['years of java experience'],'0');
  await page.getByRole('heading',{name:'Are you willing to relocate?',exact:true}).waitFor();
  await page.getByLabel('Answer for Are you willing to relocate?',{exact:true}).selectOption('No');
  await page.getByRole('button',{name:'Save this answer',exact:true}).click();
  await page.getByRole('button',{name:'Dashboard',exact:true}).click();
  await page.getByRole('button',{name:'Open LinkedIn',exact:true}).click();
  await page.getByText('LinkedIn browser opened',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Start applying',exact:true}).click();
  await page.getByText('Applying to matching jobs',{exact:true}).waitFor();
  assert.equal(commands.filter(command=>command[0]==='start').length,1);
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await page.getByRole('button',{name:'History',exact:true}).click();
  assert.equal(await page.locator('#history-view .job-title').first().textContent(),hostileTitle);
  assert.equal(await page.locator('.job-title img').count(),0);
  assert.equal(await page.evaluate(()=>window.injected),undefined);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'Export CSV',exact:true}).click();
  assert.equal((await downloadPromise).suggestedFilename(),'applications.csv');
  await mkdir(resolve('test-artifacts'),{recursive:true});
  await page.getByRole('button',{name:'Dashboard',exact:true}).click();
  await page.screenshot({path:resolve('test-artifacts/dashboard-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:resolve('test-artifacts/dashboard-mobile.png'),fullPage:true});
});

async function settingsPage(t,profile={},search={}){
  const dir=await mkdtemp(join(tmpdir(),'job-applier-settings-')),store=await createStore(dir);
  await store.saveConfig({profile,search});
  const runner={getStatus:()=>({state:'idle',todayCount:0,message:'Ready',currentJob:null}),stop:async()=>{}};
  const app=await createApp({dataDir:dir,store,runner,port:0});await app.listen();
  const browser=await chromium.launch({headless:true}),page=await browser.newPage();
  page.setDefaultTimeout(5000);
  t.after(async()=>{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});});
  await page.goto(app.url);
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  return {store,page};
}

test('browser: saving bare profile links works with Enter and persists normalized URLs',async t=>{
  const {store,page}=await settingsPage(t);
  await page.getByLabel('LinkedIn profile URL',{exact:true}).fill('www.linkedin.com/in/test-applicant');
  await page.getByLabel('Website / portfolio',{exact:true}).fill('portfolio.example/work#about');
  await page.getByLabel('Website / portfolio',{exact:true}).press('Enter');
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.linkedinUrl,'https://www.linkedin.com/in/test-applicant');
  assert.equal((await store.getConfig()).profile.website,'https://portfolio.example/work#about');
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await page.getByLabel('LinkedIn profile URL',{exact:true}).inputValue(),'https://www.linkedin.com/in/test-applicant');
});

test('browser: country and state dropdowns preserve saved values and clear stale states on country changes',async t=>{
  const {store,page}=await settingsPage(t,{country:'USA',state:'Texas'});
  const country=page.getByRole('combobox',{name:'Country',exact:true}),region=page.getByRole('combobox',{name:'State / region',exact:true});
  assert.equal(await country.inputValue(),'United States');
  assert.equal(await region.inputValue(),'Texas');
  assert.ok(await page.locator('#country-options option').count()>200);
  await region.fill('California');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.country,'United States');
  assert.equal((await store.getConfig()).profile.state,'California');
  await country.fill('Canada');await country.press('Tab');
  assert.equal(await region.inputValue(),'');
  assert.equal(await page.locator('#region-options option[value=Texas]').count(),0);
  assert.equal(await page.locator('#region-options option[value=Ontario]').count(),1);
  await region.fill('Ontario');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Settings saved'&&!document.querySelector('#save-settings').disabled);
  assert.equal((await store.getConfig()).profile.country,'Canada');
  assert.equal((await store.getConfig()).profile.state,'Ontario');
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await country.inputValue(),'Canada');assert.equal(await region.inputValue(),'Ontario');
});

test('browser: dropdowns keep unlisted saved locations until explicitly changed',async t=>{
  const {store,page}=await settingsPage(t,{country:'Custom country',state:'Custom region'});
  const country=page.getByRole('combobox',{name:'Country',exact:true}),region=page.getByRole('combobox',{name:'State / region',exact:true});
  assert.equal(await country.inputValue(),'Custom country');assert.equal(await region.inputValue(),'Custom region');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.state,'Custom region');
  await country.fill('United States');await country.press('Tab');
  assert.equal(await region.inputValue(),'');
  await region.fill('Texas');
  assert.equal(await region.inputValue(),'Texas');
});

test('browser: an invalid profile link explains the field and keeps saved settings',async t=>{
  const {store,page}=await settingsPage(t,{firstName:'Test',linkedinUrl:'https://www.linkedin.com/in/test-applicant'});
  await page.getByLabel('First name',{exact:true}).fill('Changed');
  await page.getByLabel('LinkedIn profile URL',{exact:true}).fill('not a link');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('LinkedIn profile URL must be a valid web address, such as linkedin.com/in/your-name',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.firstName,'Test');
  assert.equal(await page.getByLabel('First name',{exact:true}).inputValue(),'Changed');
  await page.getByLabel('LinkedIn profile URL',{exact:true}).fill('www.linkedin.com/in/new-applicant');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.firstName,'Changed');
  assert.equal(await page.getByLabel('LinkedIn profile URL',{exact:true}).inputValue(),'https://www.linkedin.com/in/new-applicant');
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:resolve('test-artifacts/settings-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1360,height:960});
  await page.screenshot({path:resolve('test-artifacts/settings-desktop.png'),fullPage:true});
});

test('browser: recognized location abbreviations save as full names for application choices',async t=>{
  const {store,page}=await settingsPage(t,{country:'U.S.A.',state:'TX'});
  assert.equal(await page.getByRole('combobox',{name:'Country',exact:true}).inputValue(),'United States');
  assert.equal(await page.getByRole('combobox',{name:'State / region',exact:true}).inputValue(),'Texas');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.country,'United States');
  assert.equal((await store.getConfig()).profile.state,'Texas');
});

test('browser: typed country and state values save and survive reload even without a suggestion match',async t=>{
  const {store,page}=await settingsPage(t);
  const country=page.getByRole('combobox',{name:'Country',exact:true}),region=page.getByRole('combobox',{name:'State / region',exact:true});
  await country.fill('Custom country');await country.press('Tab');
  await region.fill('Custom region');
  await region.press('Enter');
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.country,'Custom country');
  assert.equal((await store.getConfig()).profile.state,'Custom region');
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await country.inputValue(),'Custom country');assert.equal(await region.inputValue(),'Custom region');
});

test('browser: country typing updates suggestions without clearing state until a different country is committed',async t=>{
  const {store,page}=await settingsPage(t,{country:'United States',state:'Texas'});
  const country=page.getByRole('combobox',{name:'Country',exact:true}),region=page.getByRole('combobox',{name:'State / region',exact:true});
  await country.fill('Can');
  assert.equal(await country.inputValue(),'Can');assert.equal(await region.inputValue(),'Texas');
  await country.fill('USA');await country.press('Tab');
  assert.equal(await country.inputValue(),'United States');assert.equal(await region.inputValue(),'Texas');
  await country.fill('Canada');
  assert.equal(await page.locator('#region-options option[value=Ontario]').count(),1);
  assert.equal(await region.inputValue(),'Texas');
  await country.press('Tab');assert.equal(await region.inputValue(),'');
  await region.fill('ON');await region.press('Enter');
  await page.getByText('Settings saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).profile.country,'Canada');assert.equal((await store.getConfig()).profile.state,'Ontario');
});

test('browser: experience filters and keyword matching persist across reload and levels can be cleared',async t=>{
  const {store,page}=await settingsPage(t,{}, {titles:['Software Engineer'],includeKeywords:['Python','Remote'],excludeKeywords:['Unpaid']});
  const levels=page.getByRole('group',{name:'Experience level',exact:true});
  const keywordMatch=page.getByRole('combobox',{name:'Keyword matching',exact:true});
  assert.equal(await levels.getByRole('checkbox').count(),6);
  assert.equal(await levels.getByRole('checkbox',{checked:true}).count(),0);
  assert.equal(await keywordMatch.inputValue(),'all');
  assert.match(await page.locator('#include-help').textContent(),/All must match/);
  await levels.getByRole('checkbox',{name:'Internship',exact:true}).check();
  await levels.getByRole('checkbox',{name:'Entry level',exact:true}).check();
  await keywordMatch.selectOption('any');
  assert.match(await page.locator('#include-help').textContent(),/Any can match/);
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Settings saved'&&!document.querySelector('#save-settings').disabled);
  let search=(await store.getConfig()).search;
  assert.deepEqual(search.experienceLevels,['INTERNSHIP','ENTRY_LEVEL']);
  assert.equal(search.keywordMatch,'any');
  assert.deepEqual(search.titles,['Software Engineer']);
  assert.deepEqual(search.includeKeywords,['Python','Remote']);
  assert.deepEqual(search.excludeKeywords,['Unpaid']);
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await levels.getByRole('checkbox',{name:'Internship',exact:true}).isChecked(),true);
  assert.equal(await levels.getByRole('checkbox',{name:'Entry level',exact:true}).isChecked(),true);
  assert.equal(await levels.getByRole('checkbox',{checked:true}).count(),2);
  assert.equal(await keywordMatch.inputValue(),'any');
  assert.match(await page.locator('#include-help').textContent(),/Any can match/);
  await keywordMatch.selectOption('all');
  assert.match(await page.locator('#include-help').textContent(),/All must match/);
  await levels.getByRole('checkbox',{name:'Internship',exact:true}).uncheck();
  await levels.getByRole('checkbox',{name:'Entry level',exact:true}).uncheck();
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Settings saved'&&!document.querySelector('#save-settings').disabled);
  search=(await store.getConfig()).search;
  assert.deepEqual(search.experienceLevels,[]);
  assert.equal(search.keywordMatch,'all');
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await levels.getByRole('checkbox',{checked:true}).count(),0);
  assert.equal(await keywordMatch.inputValue(),'all');
});

test('browser: résumé keyword recommendations are opt-in and preserve unsaved profile and search edits',async t=>{
  const {store,page}=await settingsPage(t,{firstName:'Saved'}, {titles:['Saved role'],includeKeywords:['Remote'],excludeKeywords:['Unpaid'],experienceLevels:['ENTRY_LEVEL']});
  const read=page.getByRole('button',{name:'Read résumé',exact:true});
  assert.equal(await read.count(),1);
  assert.equal(await read.isDisabled(),true);
  assert.equal(await page.getByRole('button',{name:'Add selected keywords',exact:true}).isDisabled(),true);
  let requests=0;
  await page.route('**/api/resume/keywords',async route=>{
    requests++;assert.equal(route.request().method(),'POST');assert.deepEqual(route.request().postDataJSON(),{});
    assert.ok(route.request().headers()['x-app-token']);
    await route.fulfill({json:{resume:(await store.getConfig()).resume,keywords:['Python','SQL','JavaScript']}});
  });
  await page.getByLabel('First name',{exact:true}).fill('Unsaved');
  await page.getByLabel('Job titles',{exact:true}).fill('Backend Engineer');
  await page.getByLabel('Include keywords',{exact:true}).fill('python\nKubernetes');
  await page.getByLabel('Exclude keywords',{exact:true}).fill('Contract');
  await page.getByLabel('Upload résumé',{exact:true}).setInputFiles({name:'skills.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-test fixture')});
  const skills=page.getByRole('group',{name:'Recommended skills',exact:true});
  await skills.getByRole('checkbox',{name:'SQL',exact:true}).waitFor();
  assert.equal(requests,1);
  assert.equal(await page.getByLabel('Include keywords',{exact:true}).inputValue(),'python\nKubernetes');
  assert.equal(await page.getByLabel('First name',{exact:true}).inputValue(),'Unsaved');
  assert.equal((await store.getConfig()).search.keywordMatch,'all');
  await skills.getByRole('checkbox',{name:'Python',exact:true}).check();
  await skills.getByRole('checkbox',{name:'SQL',exact:true}).check();
  await page.getByRole('button',{name:'Add selected keywords',exact:true}).click();
  assert.equal(await page.getByLabel('Include keywords',{exact:true}).inputValue(),'python\nKubernetes\nSQL');
  assert.equal(await page.getByRole('combobox',{name:'Keyword matching',exact:true}).inputValue(),'any');
  assert.match(await page.locator('#toast').textContent(),/Save settings/);
  assert.deepEqual((await store.getConfig()).search.includeKeywords,['Remote']);
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Settings saved'&&!document.querySelector('#save-settings').disabled);
  const config=await store.getConfig();
  assert.equal(config.profile.firstName,'Unsaved');
  assert.deepEqual(config.search.titles,['Backend Engineer']);
  assert.deepEqual(config.search.includeKeywords,['python','Kubernetes','SQL']);
  assert.deepEqual(config.search.excludeKeywords,['Contract']);
  assert.deepEqual(config.search.experienceLevels,['ENTRY_LEVEL']);
  assert.equal(config.search.keywordMatch,'any');
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#save-settings').disabled);
  assert.equal(await read.isDisabled(),false);
  await read.click();await skills.getByRole('checkbox',{name:'SQL',exact:true}).waitFor();
  assert.equal(requests,2);
});

test('browser: résumé keyword extraction failure is inline and the uploaded résumé stays saved',async t=>{
  const {store,page}=await settingsPage(t);
  assert.equal(await page.getByRole('button',{name:'Read résumé',exact:true}).count(),1);
  await page.route('**/api/resume/keywords',route=>route.fulfill({status:400,json:{error:'No readable text. Upload a text-based résumé.'}}));
  await page.getByLabel('Include keywords',{exact:true}).fill('Manual skill');
  await page.getByLabel('Upload résumé',{exact:true}).setInputFiles({name:'scan.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-test fixture')});
  await page.locator('#recommendation-status').filter({hasText:'No readable text'}).waitFor();
  await page.getByText('Résumé saved',{exact:true}).waitFor();
  assert.equal((await store.getConfig()).resume.filename,'scan.pdf');
  assert.equal(await page.locator('#resume-name').textContent(),'scan.pdf');
  assert.equal(await page.getByLabel('Include keywords',{exact:true}).inputValue(),'Manual skill');
  assert.equal(await page.locator('#toast').textContent(),'Résumé saved');
  assert.equal(await page.locator('#toast').evaluate(element=>element.classList.contains('error')),false);
  assert.equal(await page.getByRole('button',{name:'Read résumé',exact:true}).isDisabled(),false);
  assert.equal(await page.getByRole('button',{name:'Add selected keywords',exact:true}).isDisabled(),true);
});

test('browser: résumé keyword responses from an older upload cannot replace current suggestions',async t=>{
  const {store,page}=await settingsPage(t);
  assert.equal(await page.getByRole('button',{name:'Read résumé',exact:true}).count(),1);
  let requests=0,releaseOlder;
  const olderPending=new Promise(resolve=>{releaseOlder=resolve;});
  await page.route('**/api/resume/keywords',async route=>{
    const request=++requests,resume=(await store.getConfig()).resume;
    if(request===2)await olderPending;
    await route.fulfill({json:{resume,keywords:request===1?['Python']:request===2?['JavaScript']:['SQL']}});
  });
  const upload=name=>page.getByLabel('Upload résumé',{exact:true}).setInputFiles({name,mimeType:'application/pdf',buffer:Buffer.from('%PDF-test fixture')});
  const skills=page.getByRole('group',{name:'Recommended skills',exact:true});
  await upload('first.pdf');await skills.getByRole('checkbox',{name:'Python',exact:true}).waitFor();
  await upload('second.pdf');
  await page.waitForFunction(()=>document.querySelector('#recommendation-status').textContent.includes('Reading'));
  assert.equal(await skills.getByRole('checkbox',{name:'Python',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Read résumé',exact:true}).isDisabled(),true);
  await page.waitForFunction(()=>!document.querySelector('#resume-upload').disabled);
  await upload('third.pdf');await skills.getByRole('checkbox',{name:'SQL',exact:true}).waitFor();
  const olderResponse=page.waitForResponse(response=>response.url().endsWith('/api/resume/keywords'));
  releaseOlder();await (await olderResponse).finished();
  assert.equal((await store.getConfig()).resume.filename,'third.pdf');
  assert.equal(await skills.getByRole('checkbox',{name:'SQL',exact:true}).count(),1);
  assert.equal(await skills.getByRole('checkbox',{name:'JavaScript',exact:true}).count(),0);
});

test('browser: real résumé extraction populates selectable keywords on desktop and mobile',async t=>{
  const {store,page}=await settingsPage(t);
  await page.getByLabel('Upload résumé',{exact:true}).setInputFiles(resolve('test/fixtures/resumes/skills.pdf'));
  const skills=page.getByRole('group',{name:'Recommended skills',exact:true});
  await skills.getByRole('checkbox',{name:'Python',exact:true}).waitFor();
  assert.equal(await skills.getByRole('checkbox').count(),7);
  assert.deepEqual((await store.getConfig()).search.includeKeywords,[]);
  await skills.getByRole('checkbox',{name:'Python',exact:true}).check();
  await skills.getByRole('checkbox',{name:'SQL',exact:true}).check();
  await page.getByRole('button',{name:'Add selected keywords',exact:true}).click();
  assert.equal(await page.getByLabel('Include keywords',{exact:true}).inputValue(),'Python\nSQL');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Settings saved'&&!document.querySelector('#save-settings').disabled);
  const search=(await store.getConfig()).search;
  assert.deepEqual(search.includeKeywords,['Python','SQL']);
  assert.equal(search.keywordMatch,'any');
  await mkdir(resolve('test-artifacts'),{recursive:true});
  await page.screenshot({path:resolve('test-artifacts/resume-keywords-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:resolve('test-artifacts/resume-keywords-mobile.png'),fullPage:true});
});
